#!/sbin/sh

. "$env"

print "Removing Knox apps and containers..."
rm -rf \
	/system/app/SecurityLogAgent \
	/system/app/RCPComponents \
	/system/app/*KNOX* \
	/system/app/*Knox* \
	/system/preloadedmm\*KNOX* \
	/system/etc/secure_storage \
	/system/container

rm -f init.container.rc
sed -i '/init.container.rc/d' init.rc

setprop ro.config.knox 0
setprop ro.config.kap false
delprop ro.config.kap_default_on
setprop ro.securestorage.support false

exit 0
