#!/sbin/sh

. "$env"

io_scheduler=sio

print "Installing kernel module symlink"
rm -rf lib
mkdir -pm 0755 lib
ln -s /system/lib/modules lib/modules

print "Setting IO scheduler to $io_scheduler"
sed -i "s|\(/sys/block/.*/scheduler[[:space:]]\+\)[a-zA-Z]\+|\1$io_scheduler|g" ./*.rc

exit 0
