#!/sbin/sh

. "$env"

io_scheduler=fiops

print "Applying kernel specific settings"

print "Setting IO scheduler to $io_scheduler"
sed -i "s|\(/sys/block/.*/scheduler[[:space:]]\+\)[a-zA-Z]\+|\1$io_scheduler|g" ./*.rc

exit 0
