#!/sbin/sh

. "$env"

print "Replacing vold..."

[ -f vold ] || abort "Unable to find vold replacement!"

replace_file /system/bin/vold vold ||
	print "Failed to replace vold!"

print "Setting keystore to exynos8890..."
setprop ro.sec.fle.encryption false
setprop ro.hardware.keystore exynos8890

print "Encryption should no longer be forced!"

exit 0
